name: Line Broadcast Test

on:
  push:
    branches:
      - main  # mainブランチにpushした際に実行

jobs:
  send-line-broadcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Send test message to all users
        run: |
          python -c "
import os
import requests

LINE_CHANNEL_ACCESS_TOKEN = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')

def send_line_broadcast(message):
    url = 'https://api.line.me/v2/bot/message/broadcast'
    headers = {
        'Authorization': f'Bearer {LINE_CHANNEL_ACCESS_TOKEN}',
        'Content-Type': 'application/json'
    }
    data = {
        'messages': [{'type': 'text', 'text': message}]
    }
    response = requests.post(url, headers=headers, json=data)
    if response.status_code == 200:
        print('Broadcast message sent successfully!')
    else:
        print(f'Error: {response.status_code}, {response.text}')

send_line_broadcast('GitHub ActionsからLINE Broadcast通知テスト中！')
          "
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
